[package]
name = "bpmn-lite-ffi-http-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.bpmn-lite-ffi-http]
path = ".."

[[bin]]
name = "owner_metadata_decode"
path = "fuzz_targets/owner_metadata_decode.rs"
test = false
doc = false
bench = false
